# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/5_finetuning_models.ipynb.

# %% auto 0
__all__ = ['PretrainedMed3dResnet10']

# %% ../nbs/5_finetuning_models.ipynb 11
from torch import nn
from functools import reduce

class PretrainedMed3dResnet10(nn.Module):

    def __init___(self, pretrained, input_dim, out_features):
        self.pretrained = pretrained

        linear_in = 512 * reduce(lambda el1, el2: el1 * el2, map(lambda el: el / 8.0, input_dim))
        self.linear = nn.Linear(linear_in, out_features, bias=False)
        self.linear.weights = nn.init.xavier_normal_(self.linear.weight)
